Add delete test too
Signed-off-by: Benoit Donneaux <benoit@leastauthority.com>

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -145,3 +145,70 @@ jobs:
           else
             echo ":heavy_check_mark: Test succeeded" >> $GITHUB_STEP_SUMMARY
           fi
+
+  test_delete:
+    name: Test delete
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Prepare environment
+        id: prepare
+        run: |
+          ssh-keygen -t ed25519 -f ./test_key -P ''
+          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
+          echo "private_key<<$EOF" >> $GITHUB_OUTPUT
+          cat ./test_key >> $GITHUB_OUTPUT
+          echo $EOF >> $GITHUB_OUTPUT
+
+          # Authorizing pub key
+          mkdir ~/.ssh && chmod 0700 ~/.ssh
+          cat ./test_key.pub >> ~/.ssh/authorized_keys
+          chmod 0600 ~/.ssh/authorized_keys
+          sudo systemctl status sshd || sudo systemctl start sshd
+
+          # Store some environment variables for the test
+          echo "TEST_USER=$(whoami)" >> $GITHUB_ENV
+          echo "TEST_WORSPACE=$(pwd)" >> $GITHUB_ENV
+
+          # Create test directories
+          mkdir -p ./test/remote
+          source='remote'
+          for content in bla bli blu; do
+            mkdir -p ./test/${source}/${content}
+            echo "Test content in ${source} ${content}" > ./test/${source}/${content}/${content}.ext
+          done
+          cp -ar ./test/remote ./test/source
+          rm -rf /test/remote/bli
+
+      - name: Call action
+        id: call
+        uses: ./
+        with:
+          src: "sftp://${{ env.TEST_USER }}:dummy@172.17.0.1${{ env.TEST_WORSPACE }}/test/remote/"
+          dst: ./test/local/
+          connect_program: 'ssh -a -x -o StrictHostKeyChecking=no -i ./test_key'
+          delete: true
+          verbose: true
+          timeout: 10
+        env:
+          VERBOSE: 2
+        continue-on-error: true
+
+      - name: Verify expected behavior
+        id: verify
+        run: |
+          diff --recursive ./test/local ./test/remote
+        continue-on-error: true
+
+      - name: Proper exit
+        run: |
+          if [ ${{ steps.prepare.outcome }} != 'success'\
+                -o ${{ steps.call.outcome }} != 'success' \
+                -o ${{ steps.verify.outcome }} != 'success' ]
+          then
+            echo ":x: Test failed" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          else
+            echo ":heavy_check_mark: Test succeeded" >> $GITHUB_STEP_SUMMARY
+          fi
