Test defaults and reverse cases
Signed-off-by: Benoit Donneaux <benoit@leastauthority.com>

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -24,7 +24,7 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      - name: Prepare key pairs
+      - name: Prepare environment
         id: prepare
         run: |
           ssh-keygen -t ed25519 -f ./test_key -P ''
@@ -39,19 +39,81 @@ jobs:
           chmod 0600 ~/.ssh/authorized_keys
           sudo systemctl status sshd || sudo systemctl start sshd
 
+          # Store some environment variables for the test
+          echo "TEST_USER=$(whoami)" >> $GITHUB_ENV
+          echo "TEST_WORSPACE=$(pwd)" >> $GITHUB_ENV
+
           # Create test directories
           mkdir -p ./test/{local,remote}
+          target='local'
           for content in bla bli blu; do
-            mkdir -p ./test/local/${content}
-            echo "Test content in ${content}" > ./test/local/${content}/${content}.ext
+            mkdir -p ./test/${target}/${content}
+            echo "Test content in ${target} ${content}" > ./test/${target}/${content}/${content}.ext
           done
+
+      - name: Call action
+        id: call
+        uses: ./
+        with:
+          remote: "sftp://${{ env.TEST_USER }}:dummy@172.17.0.1${{ env.TEST_WORSPACE }}/test/remote/"
+          local_dir: ./test/local/
+          connect_program: 'ssh -a -x -o StrictHostKeyChecking=no -i ./test_key'
+          verbose: true
+          timeout: 10
+        env:
+          VERBOSE: 2
+        continue-on-error: true
+
+      - name: Verify expected behavior
+        id: verify
+        run: |
+          diff --recursive ./test/local ./test/remote
+        continue-on-error: true
+
+      - name: Proper exit
+        run: |
+          if [ ${{ steps.prepare.outcome }} != 'success'\
+                -o ${{ steps.call.outcome }} != 'success' \
+                -o ${{ steps.verify.outcome }} != 'success' ]
+          then
+            echo ":x: Test failed" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          else
+            echo ":heavy_check_mark: Test succeeded" >> $GITHUB_STEP_SUMMARY
+          fi
+
+  test_reverse:
+    name: Test reverse
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Prepare environment
+        id: prepare
+        run: |
+          ssh-keygen -t ed25519 -f ./test_key -P ''
+          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
+          echo "private_key<<$EOF" >> $GITHUB_OUTPUT
+          cat ./test_key >> $GITHUB_OUTPUT
+          echo $EOF >> $GITHUB_OUTPUT
+
+          # Authorizing pub key
+          mkdir ~/.ssh && chmod 0700 ~/.ssh
+          cat ./test_key.pub >> ~/.ssh/authorized_keys
+          chmod 0600 ~/.ssh/authorized_keys
+          sudo systemctl status sshd || sudo systemctl start sshd
 
           # Store some environment variables for the test
           echo "TEST_USER=$(whoami)" >> $GITHUB_ENV
           echo "TEST_WORSPACE=$(pwd)" >> $GITHUB_ENV
 
-          # Test to be removed
-          ls -lA $(pwd)/test/remote
+          # Create test directories
+          mkdir -p ./test/{local,remote}
+          target='remote'
+          for content in bla bli blu; do
+            mkdir -p ./test/${target}/${content}
+            echo "Test content in ${target} ${content}" > ./test/${target}/${content}/${content}.ext
+          done
 
       - name: Call action
         id: call
@@ -61,14 +123,13 @@ jobs:
           local_dir: ./test/local/
           connect_program: 'ssh -a -x -o StrictHostKeyChecking=no -i ./test_key'
           reverse: true
-          delete: true
           verbose: true
           timeout: 10
         env:
           VERBOSE: 2
         continue-on-error: true
 
-      - name: Verify
+      - name: Verify expected behavior
         id: verify
         run: |
           diff --recursive ./test/local ./test/remote
